services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  server:
    image: ${IMAGE}
    entrypoint: [ "/entrypoint_server.sh" ]
    command: [ "uv", "run", "finstats", "--serve" ]
    environment:
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZENTOKEN: ${ZENTOKEN}
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  sync_daemon:
    image: ${IMAGE}
    entrypoint: [ "/entrypoint_sync_daemon.sh" ]
    command: [ "uv", "run", "finstats", "--daemon=sync" ]
    environment:
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZENTOKEN: ${ZENTOKEN}
      APP_PORT: 8081
    depends_on:
      - db
    restart: unless-stopped