services:
  db:
    image: 'postgres:16-alpine'
    environment: &postgres_envs
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "/entrypoint_server.sh" ]
    command: [ "uv", "run", "finstats", "--serve" ]
    environment:
      PORT: "8080"
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ZENTOKEN: PUT-YOUR-TOKEN-HERE
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  sync_daemon:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "/entrypoint_sync_daemon.sh" ]
    command: [ "uv", "run", "finstats", "--daemon=sync" ]
    environment:
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ZENTOKEN: PUT-YOUR-TOKEN-HERE
    depends_on:
      - db
    restart: unless-stopped