services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: finstats
      POSTGRES_USER: postgres
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZENTOKEN: ${ZENTOKEN}
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped